### ISSUE TITLE
Update/Fix documentation

### ISSUE THREAD

**Issue by carllerche** [carllerche/mio#433]
The state of Mio documentation has fallen behind. This is due to the API being in flux. This issue is to track the work that is needed to get the documentation to a good state. Documentation issues will be linked for reference.
- [x] Document `Poll`
- [x] Update tutorial to use `Poll` instead
- [x] Fix automated doc building (#319, #329)
- [x] Fix out of date docs (#403, #323)
- [ ] Document points of confusion (#380, #358)
- [ ] Document configuring sockets (#442, #446)
- [x] Interest options (#443)
- [ ] Upgrade (#509)

**Comment by chancez** [comment]
https://crates.fyi/crates/mio/0.5.1/ seems to be working as a working subsitite to the current one. It does seem to have the fix for #319 as I can view `EventedFd` in it.

**Comment by carllerche** [comment]
Closing due to inactivity.
